# Generated by Django 4.1.7 on 2023-03-29 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myass', '0003_alter_room_options_room_participants'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-update', '-created']},
        ),
    ]
